//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by webwatch.rc
//
#define ID_ABOUT                        0x10
#define IDD_ABOUT                       100
#define IDS_ABOUT                       101
#define IDD_MAIN                        102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_SITE_CHECK_PAGE             107
#define IDD_SITE_GENERAL_PAGE           112
#define IDI_WEBWATCH                    128
#define IDD_CHILD_HTTP_CONTENT          132
#define IDD_SITE_MU_PAGE                133
#define IDD_SET_MU                      134
#define IDD_SITE_CHECK                  135
#define IDR_MAIN_MENU                   136
#define IDD_SITEGROUP_GENERAL_PAGE      136
#define IDD_SITEGROUP_AUTO_CHECK_PAGE   137
#define IDD_CHOOSE_GROUP                138
#define IDB_TOOLBAR                     139
#define IDB_TOOLBAR_DISABLED            140
#define IDD_REGEX_EDITOR                143
#define IDD_SETTINGS_GENERAL_PAGE       144
#define IDD_SETTINGS_SITE_LIST_PAGE     145
#define IDD_SETTINGS_SITE_GROUPS_TREE_PAGE 146
#define IDD_SETTINGS_MU_PAGE            147
#define IDD_SETTINGS_CHECK_PAGE         148
#define IDD_NOTIFICATION_SOUND_SETTINGS 149
#define IDI_WEBWATCH_BURN               150
#define IDJ_ABOUT                       151
#define IDR_SITE_LIST_ACCEL             152
#define IDD_SITEGROUP_PROXY_PAGE        153
#define IDC_SITE_LIST                   1000
#define IDC_NAME                        1002
#define IDC_ADDRESS                     1003
#define IDC_SITE_TYPE                   1003
#define IDC_NOTES                       1004
#define IDC_CHECK_METHOD                1004
#define IDC_CHECK_METHOD_INFO           1005
#define IDC_STRIP_NUMBERS               1013
#define IDC_STRIP_HTML                  1014
#define IDC_HTML_STRIP_OPTIONS_GROUP    1015
#define IDC_SKIP_WHITESPACE             1016
#define IDC_SKIP_SCRIPT                 1017
#define IDC_REGEXPS                     1018
#define IDC_REMOVE_REGEX                1019
#define IDC_ADD_REGEX                   1020
#define IDC_ADD_REGEX2                  1021
#define IDC_EDIT_REGEX                  1021
#define IDC_MU_INFO                     1023
#define IDC_MU_SESSION_BUTTON           1024
#define IDC_EXPIRY_DATE                 1025
#define IDC_PROGRESS                    1026
#define IDC_SITES_CHECKED_INFO          1027
#define IDC_ABORT                       1028
#define IDC_CHECKER_LIST                1029
#define IDC_MINIMIZE                    1030
#define IDC_SITE_GROUPS_TREE            1031
#define IDC_INCLUDED_IN_PARENT_AUTOCHECK 1032
#define IDC_AUTO_CHECK_SLIDER           1033
#define IDC_AUTO_CHECK_GROUP            1034
#define IDC_GROUP_TREE                  1035
#define IDC_REGEX                       1036
#define IDC_WEBPAGE_CONTENT             1037
#define IDC_REFRESH                     1038
#define IDC_MATCH_RESULTS_STATS         1039
#define IDC_MATCH_RESULTS               1040
#define IDC_CHECK                       1045
#define IDC_UNMARK_ALL                  1046
#define IDC_STATISTICS_TEXT             1047
#define IDC_ENABLE_AUTO_SAVE            1048
#define IDC_ITEM_ACTIVATION_ACTION      1049
#define IDC_ITEM_COLOR_NAME             1050
#define IDC_COLOR_SAMPLE_TEXT           1051
#define IDC_COLOR_SET                   1052
#define IDC_MU_DAYS                     1053
#define IDC_ENABLE_NOTIFICATION         1053
#define IDC_MU_DAYS_SPIN                1054
#define IDC_CHECK_THREADS               1055
#define IDC_CHECK_THREADS_SPIN          1056
#define IDC_WRAP_CONTENT                1057
#define IDC_NOTIFICATION_TYPE           1058
#define IDC_CONFIGURE_NOTIFICATION      1059
#define IDC_SOUND_FILE                  1062
#define IDC_BROWSE                      1063
#define IDC_BEEP                        1064
#define IDC_PLAY                        1065
#define IDC_ABOUT_TEXT                  1066
#define IDC_NO_PROXY                    1067
#define IDC_USE_PROXY                   1068
#define IDC_PROXY_ADDRESS               1069
#define IDC_COMBO1                      1070
#define IDC_PROXY_TYPE                  1070
#define IDC_NO_PROXY2                   1071
#define IDC_INHERIT_PROXY               1071
#define ID_SITE_SELECT_ALL              32768
#define ID_SITE_SET_CBD                 32769
#define ID_SITE_UNSET_CBD               32770
#define ID_SITE_INVERT_CBD              32771
#define ID_SITE_ACTIVATE                32772
#define ID_SITE_ADD                     32773
#define ID_SITE_CHECK_SPECIFIC          32774
#define ID_FILE_EXIT                    32775
#define ID_SITE_BROWSE                  32776
#define ID_SITE_COPY_ADDRESS            32777
#define ID_FILE_SHOWHIDE                32778
#define ID_SITE_MARK_AS_UPDATED         32779
#define ID_SITE_UNMARK                  32780
#define ID_SITE_BEGIN_MU                32781
#define ID_SITE_END_MU                  32782
#define ID_SITE_MODIFY                  32783
#define ID_SITE_REMOVE                  32784
#define ID_SITE_MOVE_TO_GROUP           32785
#define ID_SITEGROUP_CHECK              32786
#define ID_SITEGROUP_UNMARK_ALL_SITES   32787
#define ID_SITEGROUP_REMOVE             32788
#define ID_SITEGROUP_ADD_CHILD_GROUP    32789
#define ID_SITEGROUP_MODIFY             32790
#define ID_SITEGROUP_EXPORT             32791
#define ID_SITEGROUP_MERGE_WITH_GROUP   32792
#define ID_SITEGROUP_MOVE               32793
#define ID_SITEGROUP_IMPORT_CHILD_GROUP 32794
#define ID_FILE_SETTINGS                32795
#define ID_VIEW_ORDER_BY_IMPORTANCE     32796
#define ID_VIEW_UPDATE_DIFFERENCE       32797
#define ID_SET_TEXT_COLOR               32798
#define ID_SET_BACKGROUND_COLOR         32799
#define ID_SET_DEFAULT_COLORS           32800
#define ID_TREE_EXPAND_CHILD_ITEMS      32801
#define ID_TREE_COLLAPSE_CHILD_ITEMS    32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1071
#define _APS_NEXT_SYMED_VALUE           118
#endif
#endif
