# This script will remove <p> tags following <li> tags.
# These tags are generated by Frontpage and don't look good on
# browsers other than IE.
scalar(@ARGV) > 0 or die "Usage: remp.pl <filename>";
open(DOC, $ARGV[0]) or die "Cannot open $ARGV[0] for reading: $!\n";
@doc = <DOC>;
close(DOC) or die "Cannot close $ARGV[0] : $!\n";
$doc = join("", @doc);
$doc =~ s/(<li[^>]*>[^<]*)<p[^>]*>/$1/g;
open(DOC, ">$ARGV[0]") or die "Cannot open $ARGV[0] for writing: $!\n";
print DOC $doc;
close(DOC);
